#!/bin/bash

base1=./data/trace_speed_
base2=./data/trace_time_
base3=./data/trace_num_

picdata1=./picdata/pic_speed
picdata2=./picdata/pic_time
picdata3=./picdata/pic_num
for ((i=5;i<=30;i+=5))
do
gawk -f $1 seq=$i  ${base1}$i >>${picdata1}$1
done
for ((i=150;i<=900;i+=150))
do 
gawk -f $1 seq=$i ${base2}$i >>${picdata2}$1
done

for ((i=10;i<=60;i+=10))
do 
gawk -f $1 seq=$i ${base3}$i >>${picdata3}$1
done
